#!/usr/bin/expect -f

set prompt {[#] ?$}
set address "YOU HEADSET ADDRESS HERE"

spawn sudo bluetoothctl -a
expect -re $prompt
send "power on\r"
expect -re $prompt
send "default-agent\r"
expect -re $prompt
send "disconnect $address\r"
expect -re "Successful disconnected"
expect -re $prompt
send "connect $address\r"
expect -re "Connection successful"
expect -re $prompt
send "quit\r"
expect eof
